# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='HeroDB',
            new_name='Hero',
        ),
    ]
